### ISSUE TITLE
Import feedback

### ISSUE THREAD

**Issue by GaretJax** [genetic-tools/primerbench#11]
The user should be able to see its imports and their status, along with details about parsing failures, total **new** imported primers, etc.

**Comment by AnCaTjin** [comment]
The import displays only the imported primer lists. Should single primer imports be displayed as well?

**Comment by GaretJax** [comment]
Welcome @AnCaTjin ! :-)
Adding a single primer will either succeed or fail (and tell you so), so it's easy to check if the operation succeeded. It's not so easy for a long list, hence the need to check if everything went according to the plans. The imports list will, in the future, show a full import log (what was imported, what failed, etc).

**Comment by AnCaTjin** [comment]
I just tried to upload a list not matching the criteria, to see if there is an error message, so no need to react on that. 
I think, if you add a notice about how the primer list has to look (header, ...), we could let someone test the tool with real new primers. Or is it to soon? The only problem I see is, to many primers might be rejected due to there blast results. But we will see.

**Comment by GaretJax** [comment]
I'd like to add the labs support first, so you could separate real data from "test" data, then I'd be ok with letting people use the tool.

The nice thing is that if we implement a new feature/improvement, we can easily re-analyze all primers and report the new results.

I'll check about adding an example and some additional feedback about the specific errors to the imported files.

**Comment by AnCaTjin** [comment]
Can you roughly tell me when you will add the lebs support? Are the primers seperated per account? The you could simply create a new account.
I don't understand what you mean by "implement a new feature/improvement,"

**Comment by GaretJax** [comment]
Labs support, I'd like to have something in the next couple of weeks.
Primers are not separated per account, that's what Labs will be for (so that you can share data between different people in the same Lab).

What I meant with that is that if we were to add a new thing, like for example the weights based on the SNP position on the primer, we can just rerun everything without any work involved on your part.

**Comment by GaretJax** [comment]
@AnCaTjin please check out https://genetic.tools/en/primers/imports/
You can now click on the individual imports to see the details about the different issues. Do you think that's good enough for now? I will still add an example/guide for the correct format.

**Comment by AnCaTjin** [comment]
I think it is good enough for now :) The information is actually quite interesting. How do you strip the M13 tag? In the example I see there is one reverse sequence missing after the M13 sequence has been stripped, but the primer has no M13 sequence. Is it relying on capital and small letters?

**Comment by GaretJax** [comment]
Yes, basically I remove all lowercase letters at the start of the sequence.
What would be a better algorithm? Doing it only if the sequence contains both upper and lower case letters?

**Comment by AnCaTjin** [comment]
Can't you search for the actual sequence (tgtaaaacgacggccagt, caggaaacagctatgacc)? Upper and lower case letters do not always indicate M13 sequence and "real" sequence. And in this case the primer had only lower case letters and was therefore deleted...

**Comment by GaretJax** [comment]
Is the M13 sequence always one of those two? Or can there be others?

**Comment by AnCaTjin** [comment]
At least in our lab it is always the same sequence. But there are other M13 sequences, which might be used by other labs. The sequences originate from the phage M13.

**Comment by AnCaTjin** [comment]
Ok, that is not so satisfying. But I would guess it is unsafer to extract a sequence based on upper and lower case letter. Maybe it is safer to exclude all M13 sequences (by the user) before uploading the primer list. The alternative would be to specifiy the used M13 sequence, but I guess that is much more difficult.

**Comment by GaretJax** [comment]
@AnCaTjin I'm closing this issue as feedback for imports is good enough. I opened #15 to track the M13 exclusion.
