### ISSUE TITLE
Alignment of TCGGTCCCTTTGGTACGAAA

### ISSUE THREAD

**Issue by AnCaTjin** [genetic-tools/primerbench#14]
So, I dare to create a new issue, I'm not sure about the style.
We agree this sequence is not getting perfect matches. But https://genetic.tools/en/primers/123/reverse/ has the same sequence and gets 8 hits. When I added the sequence again Test_X, I realised the primer was imported in reverse complement.

**Comment by GaretJax** [comment]
(style is perfect like this)

There is certainly some ambiguity here in how the sequences were added. Maybe something changed between the time you added the first and the second primers.

What would be the expected behavior? Am I correct assuming that a primer would match in both directions?

**Comment by AnCaTjin** [comment]
Yes and no. The primer can of course match on both strangs, but the primer orientation is important for the amplification.

**Comment by AnCaTjin** [comment]
What ist you input for the blast search of F:GGACATACGACACCTCCACC R:TCGGTCCCTTTGGTACGAAA ?
I think there is a mistake, when I import a single primer. The sequences are turned. (see test_zfyve26)

**Comment by AnCaTjin** [comment]
That is probably just the way the sequence is displayed in the primerbench/primer overview.

**Comment by GaretJax** [comment]
Yes, it is reversed there because it matches on the - strand. SNPCheck yields the same results:

Sample input:
AGRN_Ex1	GTCCCGGGGCTTTGTTCG 	CGAGGTGCACTTGTCTCCG	1

![image](https://user-images.githubusercontent.com/86236/36146015-745a0164-10b3-11e8-8f5a-3ffef90683a6.png)

![image](https://user-images.githubusercontent.com/86236/36146021-79680f7a-10b3-11e8-9d7a-4fd6acf8d7e6.png)

Results:
https://secure.ngrl.org.uk/SNPCheck/retrieve_results.htm?batchId=d197bb305f9b90b501618ec43b7b3b27

**Comment by AnCaTjin** [comment]
![primer_orientierung](https://user-images.githubusercontent.com/36272945/36147415-66a0bdf6-10b8-11e8-8694-6ccefce1fc78.jpg)

**Comment by AnCaTjin** [comment]
I assumed the sequences displayed at "my primers" were the primer sequences. But now I understand, they are only the genomic sequences at that position.

**Comment by GaretJax** [comment]
Yes, it's the same thing; if you click on the curved arrow icon (the one in the middle) you get the same thing.

Our tool always shows the sequences in ordered position (from the lower coordinate to the higher coordinate)

**Comment by GaretJax** [comment]
what is the difference between the primer sequences and the genomic sequences? Shouldn't they be the same?

**Comment by AnCaTjin** [comment]
![primer_orientierung_pfeil](https://user-images.githubusercontent.com/36272945/36147635-3d4c7b1a-10b9-11e8-969f-7fb97a187174.jpg)

**Comment by AnCaTjin** [comment]
I tried to find the primer sequence in the output (red arrows)

**Comment by GaretJax** [comment]
And it's there, right?

**Comment by GaretJax** [comment]
Just reversed because found on the - strand.

**Comment by AnCaTjin** [comment]
Everything is alright :)
I just thought the overview would display the primer sequence (as entered). But of course the sequence (genomic) has to be turned.

**Comment by GaretJax** [comment]
Cool :-) if you have suggestions to make it clearer, I’m happy to do so!

**Comment by AnCaTjin** [comment]
![primer_uebersicht](https://user-images.githubusercontent.com/36272945/36261577-17df22c6-1265-11e8-9657-16e89579c5cf.jpg)
