### ISSUE TITLE
Correctly handle M13 sequences

### ISSUE THREAD

**Issue by GaretJax** [genetic-tools/primerbench#15]
See #11 

> Ok, that is not so satisfying. But I would guess it is unsafer to extract a sequence based on upper and lower case letter. Maybe it is safer to exclude all M13 sequences (by the user) before uploading the primer list. The alternative would be to specifiy the used M13 sequence, but I guess that is much more difficult.

**Comment by GaretJax** [comment]
@AnCaTjin what about offering the user the possibility to specify the M13 sequences in the import primer form? See an example below:
![image](https://user-images.githubusercontent.com/86236/36089754-b1857572-0fdd-11e8-82de-ce49c8c77c42.png)

(the field could even be prepopulated with the last sequences used on an import by the same user or lab)

**Comment by AnCaTjin** [comment]
That's what I meant above :)
If it is not to difficult to implement, that would be the ideal solution.
But I would suggest to keep the formulation more open. Other sequences might not (probably rare cases) be M13, as they derive from some other phage.

**Comment by GaretJax** [comment]
I'll implement it, is not too hard.

Suggestions about the formulation are welcome. ;-)

**Comment by AnCaTjin** [comment]
"common primer sequence (e.g. M13)"?
"universal sequencing primer sequence"?

**Comment by GaretJax** [comment]
This should be fixed. You're welcome to take it for a spin: https://genetic.tools/labs/test/primers/imports/

**Comment by GaretJax** [comment]
Just to make sure: the common sequences are removed only from the start of the primer, not if they happen in the middle or at the end.

**Comment by AnCaTjin** [comment]
Yes, they are only at the start of a primer, however these sequences are used because they are supposed to be unique. They do not match anywhere in the human genome. Therefore they should not be part of any specific primer sequence.

**Comment by AnCaTjin** [comment]
I think I would prefer "universal primer sequence (e.g. M13) :)

**Comment by GaretJax** [comment]
Done.

**Comment by GaretJax** [comment]
I'll mark this one as solved. Feel free to add a comment if you think this needs further improvement.
