### ISSUE TITLE
Revamp the analysis details page

### ISSUE THREAD

**Issue by GaretJax** [genetic-tools/primerbench#6]

**Comment by AnCaTjin** [comment]
I have a suggestion (nothing urgent, just something that would be nice) for the analysis details page. When the mouse is over a variant frequency it is highlighted. It would be nice, if the SNP would be highlighted in the assembly overview at the top, when the user clicks on the SNP.

**Comment by GaretJax** [comment]
Hi @AnCaTjin, sorry for the lack of news in the last week. I've been quite busy with other stuff (the semester projects are starting ;-).

I've been able to work a bit on a new idea for the primer details page. Instead of showing the details for the forward sequence and the reverse sequence, the idea is to:

1. Show a primer overview page with all the exact hits we found for both sequences (see example below for Eva's primer)
2. Allow to show the details we showed before for the sequences, but this time for each exact hit.

I didn't have time to finish this up and put it online, but I should be able to do that next week.

![image](https://user-images.githubusercontent.com/86236/36589312-2cb09a1e-188b-11e8-8bfa-cdb9f424ad90.png)
![image](https://user-images.githubusercontent.com/86236/36589322-336ffd5e-188b-11e8-8646-f77f1c94c345.png)

**Comment by GaretJax** [comment]
I guess one possible enhancement here is to show more details in the exact hits list (like number of variants and MAFs).

I'm also putting it here otherwise I forget, we should display a warning in the hists list if the hit occurred in on an alternate loci or on a patch (and any other non-primary-assembly hit).

**Comment by AnCaTjin** [comment]
Hi! We have students here this week as well. 
I like the idea to show all the exact hits on one page, maybe than the user could accept the primers anyway. I am  looking forward to try the new features.

**Comment by GaretJax** [comment]
Hi @AnCaTjin, finally had the time to work a bit on the per-hit analysis page.
This is still work in progress, I need to re-add the checks, but what you can see above is now working (example for Eva's primer: https://genetic.tools/labs/huge-wue/primers/190/).

As said, I'd like to bring back the checks, display the details on the hit detail page and a summary on the primer detail page (for each hit). While I'm at it, I'll also look into making those checks configurable on a per-organization/per-primer basis.

**Comment by GaretJax** [comment]
Did some additional enhancements to the hit details page:

- Added Gnomad and Ensembl references
- Added more details about the primer/sequence/hit
- Added check results for this particular hit (can dynamically be adjusted per-organisation/per-primer... not yet exposed to the user)
- Added raw data export
- Nicer layout and user interface

Before:
![image](https://user-images.githubusercontent.com/86236/37405485-0745dd52-2795-11e8-916a-b6e333dc15a3.png)

After:
![image](https://user-images.githubusercontent.com/86236/37405507-15d26b1a-2795-11e8-955b-d1332ef4598f.png)

P.S.: I might understand why you say that the total MAF makes no sense... we're not summing all the MAFs together... currently it's just the sum of the max MAF for each variant, but it could be made even better by summing all MAFs across all variants by population, and then retaining the maximum. TO be discussed...

**Comment by AnCaTjin** [comment]
I like the new layout. It is easy to grasp, if the primer is fine everything is green, if not a few clicks bring all the information you need to make a decision to use the primer or to discard it.
Unfortunatly, I do not quite understand what you mean by your PS. I thought you were summing all MAFs of all variants and all populations?

**Comment by GaretJax** [comment]
I'll close this for now, as the original issue has been resolved.
